private_gsheets_url = "https://docs.google.com/spreadsheets/d/1zxlIEnIs_EEaKpOpdNoBy4mkWyCQQaWN/edit#gid=2068205215"

[gcp_service_account]

type = "service_account"
project_id ="hale-courage-380010"
private_key_id="65ecb87236c2fa9c80d4f82b629fa7e24e646d65"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCk0CSmHRlk+cR7
ODTePRAQd4b2ajhxgqTUfNiJP15rk6upCIWQ0BMv7dOP8pgyXW36xDpYowji8DWZ
s93Q8NbAbBo6sQhvxv3TFVzqt9IbO6+RpTmGS8R8XHLSQXYqWmTws4+PGbI4llIc
oodvbM7xF1bhlk4E+/dwCvGeM+DYBxXP/6R1uV1DrIcwa73rYnwmH721n3/S8DeV
eAYbFdX9xSAPjMl200AN9CxtgYM1bYdAlk35+Nu/zYHbOxJaUCkHhRuYfaenZeRm
wHeDLegxvNx45ITITLhP3iPNURCYol6+u7FMKuOqUqeOCJysYVYZ9kuWOVkeKHWY
KcGaO7DhAgMBAAECggEAEoRXgcRQ3Jaapn9vooJ4zL4pJIQATccwWWFM0Mq/rdV8
WrRG5rjCAcdg1tJE8EUCp23RjQYwPZMLFUxEloY15+OdZM0MFhw6MLOR6hsiA4ZG
rlXtFcjAeCUeOhTkalNtS4UuaBT/1Y9qBVFAvITx5oYemvTQqjWxnLMrZ1YLzn7Q
cr50j6FKDiwljqJ60X6D4I8m22u+ZJzcPkTCVKuSirJtAbZO8gjdBrwqW8eBTld5
5zvDN53y1napc+9lM/XxAW4b5bTL2Dqf6TwHZ6Pu9O4P14syOb6DadFpzFG5vKJX
q2OGIEyuXBbt8voq6M95GzZ4Y98uNXnO7eVSwiSKwwKBgQDTqkvhSpaeMQVrnfge
9vtcchYKJl8F2MHjx87ptDvQt69C5U7wnL0Pql9X2t5g0UOoTPIYSXQ3Q9AJ2Ssr
rHSlm6zYd9u17fVsZHOKAqI/atgT5oHllBS1azlWsrwXZz72gRiLCvIv1b61epZe
esmOH/pRpfJQdDJCdcgP55jyDwKBgQDHVZYePsRrzMTAL+bF47tS78YEeo/FRAww
xrlvy1/DrlfXDX1H7axdorrqQhXY5FkNvd+Qy+pCIrB9hWntV5aPBstekkUMkeXi
x5AJOq+B1JABNGO7G2pU/cCEwARlXx3ZiOKZkVyhGT1g7JzO663ievmzha7mPopp
Z8Hp/lxeDwKBgEJ7xhPAouiTSzmPR8UqHK/f4c5UWRp0CAqs0vATPYqEd5dSgWYQ
RU4rXIEy7RCKCm9No+k/ATLuqOS/AtFX/Nebu0HO/AL7+E+Qib36r82tmKs/huN+
jLajNEJoJ65OLresuvHJgWLHB3znQV3xwWdT4gNNVXwx0yuO5UUhoKe/AoGAWHwh
m2N5hfDsFfQtmQKykOpnGG3fjE3cq3pLrti0tgSacZhHWLqknRwzpPGZCSK0dWkn
6PrcDmefuNiUYQtUhkEZ3e1IQYAycCzuP2qRpixZkG9VJiXRWdEauNMUIHvMoFgn
XswsNkch+/iM0z3DfpngZlSdgw+YGZo5dkm3bvkCgYATrHkhBRN0smzkuJJCbWSU
yg2qU7KvvI+VBUty6TGOZ3hTH1FMgqBPKjLRo1vbvSoebQhfeY4WLd0vKxQdSSb9
3YjoNQYmHX1QJ9WHF9YIjfnmBxQwTeIqJSBJqaMOvBQLWjfN+DrWQ6yoO8ZJ/eNW
UgX6atdIuGgI9xQlA7WwKA==
-----END PRIVATE KEY-----
"""
client_email = "quickbook-service@hale-courage-380010.iam.gserviceaccount.com"
client_id = "114867058452442207950"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/quickbook-service%40hale-courage-380010.iam.gserviceaccount.com"
